### ISSUE TITLE
Symbol not found: _exsltDateXpathCtxtRegister - lxml/etree.cpython-39-darwin.so

### ISSUE THREAD

**Issue by marcdk** [digital-engineering/airbnb-scraper#15]
Hi guys

Anybody experience this issue perhaps?
```
Traceback (most recent call last):
  File "/Users/***/workspace/airbnb-scraper/env/bin/scrapy", line 5, in <module>
    from scrapy.cmdline import execute
  File "/Users/***/workspace/airbnb-scraper/env/lib/python3.9/site-packages/scrapy/__init__.py", line 12, in <module>
    from scrapy.spiders import Spider
  File "/Users/***/workspace/airbnb-scraper/env/lib/python3.9/site-packages/scrapy/spiders/__init__.py", line 11, in <module>
    from scrapy.http import Request
  File "/Users/***/workspace/airbnb-scraper/env/lib/python3.9/site-packages/scrapy/http/__init__.py", line 11, in <module>
    from scrapy.http.request.form import FormRequest
  File "/Users/***/workspace/airbnb-scraper/env/lib/python3.9/site-packages/scrapy/http/request/form.py", line 10, in <module>
    import lxml.html
  File "/Users/***/workspace/airbnb-scraper/env/lib/python3.9/site-packages/lxml/html/__init__.py", line 53, in <module>
    from .. import etree
ImportError: dlopen(/Users/***/workspace/airbnb-scraper/env/lib/python3.9/site-packages/lxml/etree.cpython-39-darwin.so, 2): Symbol not found: _exsltDateXpathCtxtRegister
  Referenced from: /Users/***/workspace/airbnb-scraper/env/lib/python3.9/site-packages/lxml/etree.cpython-39-darwin.so
  Expected in: flat namespace
 in /Users/***/workspace/airbnb-scraper/env/lib/python3.9/site-packages/lxml/etree.cpython-39-darwin.so
```

Some system environment info
```
System Version: macOS 11.3.1 (20E241)
Kernel Version: Darwin 20.4.0
Python Version: 3.9.2
```

**Comment by digitalengineering** [comment]
Thanks for the report. Only Linux is currently supported. If I had a Mac, I could try to make it work there too..
