### ISSUE TITLE
Can't run examples

### ISSUE THREAD

**Issue by mbrylewi** [digital-engineering/airbnb-scraper#17]
2021-12-05 10:59:34 [scrapy.core.engine] ERROR: Error while obtaining start requests
Traceback (most recent call last):
  File "/home/maciej/env/lib/python3.8/site-packages/scrapy/core/engine.py", line 129, in _next_request
    request = next(slot.start_requests)
  File "/home/maciej/airbnb-scraper/deepbnb/spiders/airbnb.py", line 136, in start_requests
    yield self.__explore_search.api_request(self.__query, params, self.__explore_search.parse_landing_page)
  File "/home/maciej/airbnb-scraper/deepbnb/api/ExploreSearch.py", line 63, in api_request
    headers = self._get_search_headers()
  File "/home/maciej/airbnb-scraper/deepbnb/api/ApiBase.py", line 51, in _get_search_headers
    return required_headers | {
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'

**Comment by kevinle-1** [comment]
Requires Python3.9+🙂
